(define
    (problem problem_09_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 G W R)
(cube2 O B Y)
(cube3 R B W)
(cube4 G O W)
(cube5 Y B R)
(cube6 B W O)
(cube7 R Y G)
(cube8 O Y G)
(edge12 W B)
(edge24 O Y)
(edge34 R G)
(edge13 Y R)
(edge15 R W)
(edge26 O G)
(edge48 B R)
(edge37 W O)
(edge56 W G)
(edge68 Y B)
(edge78 B O)
(edge57 Y G)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)