(define
    (problem problem_15_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 G Y O)
(cube2 B R Y)
(cube3 G R W)
(cube4 W G O)
(cube5 Y R G)
(cube6 O Y B)
(cube7 B W O)
(cube8 R B W)
(edge12 O W)
(edge13 W B)
(edge15 Y R)
(edge24 R G)
(edge26 B Y)
(edge34 B O)
(edge37 G W)
(edge48 R B)
(edge56 O G)
(edge57 R W)
(edge68 Y G)
(edge78 O Y)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)