(define
    (problem problem_11_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 B Y R)
(cube2 G O Y)
(cube3 Y R G)
(cube4 W O B)
(cube5 W R B)
(cube6 Y B O)
(cube7 G W R)
(cube8 W O G)
(edge12 W B)
(edge24 W R)
(edge34 G O)
(edge13 R G)
(edge15 B O)
(edge26 Y O)
(edge48 O W)
(edge37 Y G)
(edge56 R B)
(edge68 W G)
(edge78 B Y)
(edge57 Y R)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)