(define
    (problem problem_10_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 O G Y)
(cube2 W G R)
(cube3 R B W)
(cube4 O B W)
(cube5 B R Y)
(cube6 R Y G)
(cube7 O W G)
(cube8 O B Y)
(edge12 O W)
(edge13 R W)
(edge15 Y R)
(edge24 Y B)
(edge26 W G)
(edge34 O Y)
(edge37 R B)
(edge48 O B)
(edge56 R G)
(edge57 O G)
(edge68 W B)
(edge78 G Y)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)