(define
    (problem problem_20_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 G R Y)
(cube2 O G W)
(cube3 G O Y)
(cube4 B R W)
(cube5 B O W)
(cube6 O Y B)
(cube7 B Y R)
(cube8 W G R)
(edge12 G R)
(edge24 B R)
(edge34 W O)
(edge13 W R)
(edge15 B Y)
(edge26 Y O)
(edge48 W B)
(edge37 G Y)
(edge56 R Y)
(edge68 B O)
(edge78 G O)
(edge57 G W)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)