(define
    (problem problem_08_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 G R Y)
(cube2 B R Y)
(cube3 W O G)
(cube4 Y O G)
(cube5 G R W)
(cube6 B R W)
(cube7 W O B)
(cube8 Y O B)
(edge12 O W)
(edge24 Y G)
(edge34 O G)
(edge13 W G)
(edge15 R Y)
(edge26 R G)
(edge48 R B)
(edge37 R W)
(edge56 O Y)
(edge68 Y B)
(edge78 O B)
(edge57 W B)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)