(define
    (problem problem_17_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 O W G)
(cube2 R Y B)
(cube3 O B Y)
(cube4 G W R)
(cube5 O W B)
(cube6 Y G R)
(cube7 W B R)
(cube8 O Y G)
(edge12 O G)
(edge13 W R)
(edge15 O W)
(edge24 Y B)
(edge26 G Y)
(edge34 B R)
(edge37 R Y)
(edge48 W B)
(edge56 W G)
(edge57 Y O)
(edge68 B O)
(edge78 G R)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)