(define
    (problem problem_18_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 W R G)
(cube2 Y R G)
(cube3 Y B R)
(cube4 R W B)
(cube5 O Y G)
(cube6 O Y B)
(cube7 W G O)
(cube8 O W B)
(edge12 R W)
(edge13 W G)
(edge15 Y G)
(edge24 W B)
(edge26 Y O)
(edge34 B Y)
(edge37 R B)
(edge48 O W)
(edge56 G O)
(edge57 G R)
(edge68 O B)
(edge78 R Y)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)