(define
    (problem problem_11_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 G Y O)
(cube2 B R Y)
(cube3 G Y R)
(cube4 R G W)
(cube5 B O W)
(cube6 O Y B)
(cube7 B R W)
(cube8 G W O)
(edge12 R Y)
(edge13 O G)
(edge15 R B)
(edge24 B Y)
(edge26 O Y)
(edge34 W O)
(edge37 R G)
(edge48 Y G)
(edge56 W R)
(edge57 B W)
(edge68 G W)
(edge78 B O)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)