(define
    (problem problem_15_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 G O W)
(cube2 B O W)
(cube3 R W G)
(cube4 O Y B)
(cube5 R Y B)
(cube6 B R W)
(cube7 R Y G)
(cube8 G O Y)
(edge12 R W)
(edge24 R G)
(edge34 O Y)
(edge13 R Y)
(edge15 O B)
(edge26 O W)
(edge48 G W)
(edge37 O G)
(edge56 B W)
(edge68 Y B)
(edge78 B R)
(edge57 G Y)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)