(define
    (problem problem_01_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 B W O)
(cube2 G W O)
(cube3 R Y B)
(cube4 O Y B)
(cube5 B W R)
(cube6 G W R)
(cube7 R Y G)
(cube8 O Y G)
(edge12 W O)
(edge13 R B)
(edge15 B W)
(edge24 O B)
(edge26 G W)
(edge34 Y B)
(edge37 R Y)
(edge48 O Y)
(edge56 W R)
(edge57 R G)
(edge68 O G)
(edge78 Y G)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)