(define
    (problem problem_05_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 G R Y)
(cube2 B Y O)
(cube3 W G R)
(cube4 Y O G)
(cube5 R B W)
(cube6 B Y R)
(cube7 B W O)
(cube8 G W O)
(edge12 R Y)
(edge13 Y B)
(edge15 R B)
(edge24 O G)
(edge26 W B)
(edge34 G R)
(edge37 G Y)
(edge48 Y O)
(edge56 W G)
(edge57 R W)
(edge68 O B)
(edge78 W O)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)