(define
    (problem problem_20_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 B Y R)
(cube2 G Y R)
(cube3 B Y O)
(cube4 R G W)
(cube5 Y G O)
(cube6 G O W)
(cube7 W B R)
(cube8 W B O)
(edge12 R Y)
(edge13 W B)
(edge15 G R)
(edge24 R B)
(edge26 B Y)
(edge34 O G)
(edge37 Y O)
(edge48 O B)
(edge56 W G)
(edge57 R W)
(edge68 G Y)
(edge78 O W)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)