(define
    (problem problem_06_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 B O Y)
(cube2 O W B)
(cube3 R W G)
(cube4 G R Y)
(cube5 Y G O)
(cube6 B R W)
(cube7 G O W)
(cube8 Y B R)
(edge12 W B)
(edge24 O B)
(edge34 W G)
(edge13 Y G)
(edge15 R W)
(edge26 B R)
(edge48 O W)
(edge37 G O)
(edge56 R G)
(edge68 Y R)
(edge78 Y B)
(edge57 Y O)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)