(define
    (problem problem_10_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 B Y R)
(cube2 R B W)
(cube3 W G R)
(cube4 B W O)
(cube5 Y R G)
(cube6 W G O)
(cube7 O G Y)
(cube8 O B Y)
(edge12 Y B)
(edge24 O B)
(edge34 R B)
(edge13 Y O)
(edge15 Y R)
(edge26 O W)
(edge48 G O)
(edge37 B W)
(edge56 Y G)
(edge68 R W)
(edge78 R G)
(edge57 W G)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)