(define
    (problem problem_17_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 W R G)
(cube2 G Y R)
(cube3 W O G)
(cube4 B Y R)
(cube5 Y G O)
(cube6 Y B O)
(cube7 B R W)
(cube8 B O W)
(edge12 G R)
(edge24 O W)
(edge34 O B)
(edge13 W B)
(edge15 Y G)
(edge26 R W)
(edge48 G W)
(edge37 O G)
(edge56 Y O)
(edge68 Y B)
(edge78 R B)
(edge57 Y R)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)