(define
    (problem problem_05_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 Y O G)
(cube2 W O G)
(cube3 B Y O)
(cube4 B R W)
(cube5 W G R)
(cube6 W O B)
(cube7 R B Y)
(cube8 Y R G)
(edge12 O G)
(edge24 Y B)
(edge34 R W)
(edge13 B O)
(edge15 B W)
(edge26 O Y)
(edge48 O W)
(edge37 R B)
(edge56 G R)
(edge68 G W)
(edge78 Y G)
(edge57 R Y)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)