(define
    (problem problem_19_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 R Y G)
(cube2 G W O)
(cube3 Y G O)
(cube4 O B W)
(cube5 R Y B)
(cube6 R G W)
(cube7 O Y B)
(cube8 B W R)
(edge12 B O)
(edge13 W O)
(edge15 G W)
(edge24 B W)
(edge26 G O)
(edge34 Y R)
(edge37 R B)
(edge48 Y O)
(edge56 G R)
(edge57 W R)
(edge68 B Y)
(edge78 Y G)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)