(define
    (problem problem_14_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 Y G R)
(cube2 Y G O)
(cube3 R B W)
(cube4 W G O)
(cube5 Y O B)
(cube6 W R G)
(cube7 O B W)
(cube8 Y B R)
(edge12 O B)
(edge13 Y G)
(edge15 O W)
(edge24 R W)
(edge26 B R)
(edge34 W B)
(edge37 Y B)
(edge48 W G)
(edge56 R G)
(edge57 R Y)
(edge68 O G)
(edge78 Y O)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)