(define
    (problem problem_19_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 O B W)
(cube2 W G R)
(cube3 B R Y)
(cube4 O Y B)
(cube5 W O G)
(cube6 W B R)
(cube7 R Y G)
(cube8 G O Y)
(edge12 O Y)
(edge24 Y B)
(edge34 O G)
(edge13 G R)
(edge15 O W)
(edge26 W R)
(edge48 G Y)
(edge37 W B)
(edge56 B O)
(edge68 B R)
(edge78 R Y)
(edge57 G W)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)