(define
    (problem problem_12_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 W G O)
(cube2 G R W)
(cube3 G O Y)
(cube4 R W B)
(cube5 W B O)
(cube6 Y R B)
(cube7 R Y G)
(cube8 B Y O)
(edge12 O B)
(edge24 Y G)
(edge34 G W)
(edge13 R W)
(edge15 O W)
(edge26 Y B)
(edge48 G R)
(edge37 R Y)
(edge56 Y O)
(edge68 O G)
(edge78 B R)
(edge57 W B)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)