(define
    (problem problem_07_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 G R Y)
(cube2 R B W)
(cube3 B R Y)
(cube4 W G O)
(cube5 O Y G)
(cube6 Y B O)
(cube7 R G W)
(cube8 B O W)
(edge12 G O)
(edge13 Y G)
(edge15 B R)
(edge24 O Y)
(edge26 B W)
(edge34 Y B)
(edge37 R G)
(edge48 W G)
(edge56 B O)
(edge57 R W)
(edge68 R Y)
(edge78 O W)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)