(define
    (problem problem_02_01)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 (cube1 Y B O)
(cube2 W R B)
(cube3 Y G O)
(cube4 W O B)
(cube5 R W G)
(cube6 O W G)
(cube7 B Y R)
(cube8 G Y R)
(edge12 R B)
(edge24 W B)
(edge34 O B)
(edge13 Y O)
(edge15 R W)
(edge26 O W)
(edge48 G Y)
(edge37 B Y)
(edge56 W G)
(edge68 O G)
(edge78 Y R)
(edge57 R G)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)